// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:c093bb08-10a2-4e9a-bb26-04382a7114e5',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'web-hosting-mobilehub-1029940181',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dfmv2279xqznx.cloudfront.net',
    'aws_mobile_analytics_app_id': '1257245938994accacde22a9bda0ebbe',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'c6eedbf2-c89e-448a-9e4f-74eab5c7d50c',
    'aws_project_name': 'web-2018-07-28-11-52-24',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'web-mobilehub-1029940181',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_tUkzsspPi',
    'aws_user_pools_web_client_id': '7lniin3to038b7efenodeij5j2',
}

export default awsmobile;
